### ISSUE TITLE
Map.addLayer results in CRS error

### ISSUE THREAD

**Issue by cjobim** [gee-community/qgis-earthengine-plugin#102]
I'm unsure whether the error is mine or from the code, but I am getting this error with the demonstration code shown on the plugin's webpage upon running the Map.addLayer command (the CRS used in this project is UTM projected in zone 20 north, WGS84): 

```
Map.addLayer(image,{'min':500,'max':5000,'gamma':1.4,'bands':['B4','B3','B2']},'image')
Traceback (most recent call last):
  File "C:\Users\cjobim\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 338, in _execute_cloud_call
    return call.execute(num_retries=num_retries)
  File "C:\Users\cjobim\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\cjobim\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/maps?fields=name&alt=json returned "GeometryConstructors.Point, argument 'crs': Invalid type.
Expected type: Projection.
Actual type: String.
Actual value: EPSG:32620">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS 3.16\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/Users/cjobim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\Map.py", line 24, in addLayer
    add_or_update_ee_layer(eeObject, visParams, name, shown, opacity)
  File "C:/Users/cjobim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 144, in add_or_update_ee_layer
    layer = add_or_update_ee_image_layer(image, name, shown, opacity)
  File "C:/Users/cjobim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 157, in add_or_update_ee_image_layer
    layer = add_ee_image_layer(image, name, shown, opacity)
  File "C:/Users/cjobim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 47, in add_ee_image_layer
    url = "type=xyz&url=" + get_ee_image_url(image)
  File "C:/Users/cjobim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 19, in get_ee_image_url
    map_id = ee.data.getMapId({'image': image})
  File "C:\Users\cjobim\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 591, in getMapId
    body=request))
  File "C:\Users\cjobim\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 340, in _execute_cloud_call
    raise _translate_cloud_exception(e)
ee.ee_exception.EEException: GeometryConstructors.Point, argument 'crs': Invalid type.
Expected type: Projection.
Actual type: String.
Actual value: EPSG:32620
```
Does anyone have pointers on how to solve this? Thanks

**Comment by gena** [comment]
The error looks a bit weird, it says something about Point constructor, do you have the whole code snippet you ruin in QGIS python script?

I've just tried in QGIS 3.18 - seems to work:
![image](https://user-images.githubusercontent.com/169821/136216666-c5c7cf12-bbc1-4153-8747-88c336e8d700.png)
