### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by aribavertex** [gee-community/qgis-earthengine-plugin#107]
Hello,

I'm writing to you in reference to an error displayed to me when typing in the console import ee:

ModuleNotFoundError: No module named 'fcntl'

I've installed the latest version of the plugin (0.0.4) in QGIS 3.16.4 on a Windows 10 machine.

The console returns the following message, do you know what the problem may be and please help me to find a possible solution?

The truth is that it's been more than a year since I last used the plugin (0.0.2 version), but it worked without a problem; but now that I've used again the console returned me this message.

Same message when upgrading to the latest plugin version (0.0.4)

I've tried to work with the plugin on the same computer on QGIS 3.10.3, 3.16.4 and 3.22.4 with the same result.

Thank you so much.

Antoni Riba

Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/Users/Antoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\Antoni\AppData\Roaming\Python\Python37\site-packages\ee\__init__.py", line 1, in <module>
    from .main import main
  File "C:/Users/Antoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\Antoni\AppData\Roaming\Python\Python37\site-packages\ee\main.py", line 5, in <module>
    import blessings
  File "C:/Users/Antoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\Antoni\AppData\Roaming\Python\Python37\site-packages\blessings\__init__.py", line 7, in <module>
    from fcntl import ioctl
  File "C:/Users/Antoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'fcntl'

**Comment by gena** [comment]
It looks like you have another Python installed with the default path (PATH, PYTHONPATH) which differs from the QGIS `"C:\Users\Antoni\AppData\Roaming\Python\Python37\...'`, that causes troubles. Try uninstalling that or install it without setting it as a default python.

**Comment by aribavertex** [comment]
Thank you so much for answer in such a short time!!!
I'll try to do what you recommend me.

**Comment by gena** [comment]
Let me know if this issue is fixed, especially in v0.0.5

**Comment by ricds** [comment]
i am having this error on my windows machine, it seems this 'fcntl' is ubuntu only? is there a way to solve it ? i cannot do import ee without getting that error...

**Comment by lgeibel** [comment]
I am having the same problem - is there any workaround for this so we can run this on a windows machine?
