### ISSUE TITLE
v 0.0.5 classFactor error

### ISSUE THREAD

**Issue by cczablan1** [gee-community/qgis-earthengine-plugin#113]
Hi, i need help with this, I am using the v.0.0.5 (since v0.0.4 struggles produces a Error 400)

```
Couldn't load plugin 'qgis-earthengine-plugin-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'ee_plugin' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Cristan Dave Zablan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-earthengine-plugin-master\__init__.py", line 62, in classFactory
    import_ee()
  File "C:\Users/Cristan Dave Zablan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-earthengine-plugin-master\__init__.py", line 30, in import_ee
    from ee_plugin.ee_auth import authenticate
  File "C:\Users/Cristan Dave Zablan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 33, in __wrapping_ee_import__
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ee_plugin'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.5-Białowieża Białowieża, c27231782f 

Python Path:
C:\Users/Cristan Dave Zablan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/Cristan Dave Zablan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Cristan Dave Zablan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.2-py3.9-win-amd64.egg
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Cristan Dave Zablan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Cristan Dave Zablan\AppData\Local\acatama\python39
C:\Users\Cristan Dave Zablan\AppData\Local\acatama\python39\lib\site-packages
C:\Users\Cristan Dave Zablan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Cristan Dave Zablan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\Cristan Dave Zablan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users/Cristan Dave Zablan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
C:\Users\Cristan Dave Zablan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis-earthengine-plugin-master\extlibs_windows
C:\Users\Cristan Dave Zablan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis-earthengine-plugin-master\extlibs_windows
C:\Users\Cristan Dave Zablan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis-earthengine-plugin-master\extlibs_windows
C:\Users\Cristan Dave Zablan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis-earthengine-plugin-master\extlibs_windows
C:\Users\Cristan Dave Zablan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis-earthengine-plugin-master\extlibs_windows
```

**Comment by gena** [comment]
Yes, investigating this right now, please uninstall v0.0.5 and re-install from experimental. Then authenticate via Python before starting QGIS. In your main Python (not in QGIS!) run:

```
> pip install --upgrade earthengine-api
> earthengine authenticate

```

**Comment by cczablan1** [comment]
How do I reinstall from experimental?

**Comment by gena** [comment]
... it looks like it's also not approved, try this one (installing from zip). There are no new features, only more recent earthengine library

[ee_plugin-0.0.5.zip](https://github.com/gee-community/qgis-earthengine-plugin/files/8984228/ee_plugin-0.0.5.zip)

**Comment by cczablan1** [comment]
Thank you so much, that worked! <3
