### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'cv2'


### ISSUE THREAD

**Issue by M00nsocket** [gee-community/qgis-earthengine-plugin#123]
Couldn't load plugin 'QGIS_FMV' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS 3.28.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\__init__.py", line 49, in classFactory
    from .QgsFmv import Fmv
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS 3.28.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\QgsFmv.py", line 35, in <module>
    from QGIS_FMV.manager.QgsManager import FmvManager
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS 3.28.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\manager\QgsManager.py", line 20, in <module>
    from QGIS_FMV.player.QgsFmvDrawToolBar import DrawToolBar as draw
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS 3.28.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\player\QgsFmvDrawToolBar.py", line 15, in <module>
    from QGIS_FMV.utils.QgsFmvUtils import (GetSensor,
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS 3.28.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\utils\QgsFmvUtils.py", line 61, in <module>
    from cv2 import (COLOR_BGR2RGB,
  File "C:\Users/gregp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS 3.28.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'cv2'

```
ee_plugin 0.0.5, QGIS 3.28.2-Firenze on Windows 10

**Comment by gena** [comment]
The error seems to be related to the QgisFmv plugin, and as the error says, it seems to be missing the OpenCV library.
