### ISSUE TITLE
Uncaught subprocess.CalledProcessError: Command '['python3', '-m', 'pip', 'install', '--upgrade', '--force-reinstall', '--no-cache-dir', 'pillow']' returned non-zero exit status 1.


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [gee-community/qgis-earthengine-plugin#124]
Impossibile caricare il plugin 'QCopycanvas' a causa di un errore chiamando il metodo classFactory()
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\QCopycanvas\__init__.py", line 35, in classFactory
    from .QCopycanvas import QCopycanvas
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\QCopycanvas\QCopycanvas.py", line 41, in <module>
    check()
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\QCopycanvas\install_packages\check_dependencies.py", line 31, in check
    subprocess.check_call(['python3', '-m', 'pip', 'install', '--upgrade', '--force-reinstall',
  File "C:\OSGeo4W\apps\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3', '-m', 'pip', 'install', '--upgrade', '--force-reinstall', '--no-cache-dir', 'pillow']' returned non-zero exit status 1.

```
ee_plugin 0.0.6, QGIS 3.28.4-Firenze on Windows 10

**Comment by XavierCLL** [comment]
Hi @UrbanPlan-LDB 

Same here the error is not due to GEE Plugin, a question the plugins 'QCopycanvas' and 'HotspotAnalysis' work well if the GEE plugin is not installed?
