### ISSUE TITLE
Uncaught TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [gee-community/qgis-earthengine-plugin#126]
Impossibile caricare il plugin 'spanners_plugin'
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\__init__.py", line 1, in <module>
    from .mainPlugin import SPANNERSPlugin
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\mainPlugin.py", line 31, in <module>
    from .views.pluginDialog import PluginDialog
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\views\pluginDialog.py", line 33, in <module>
    from .ogdfAnalysisView import OGDFAnalysisView
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\views\ogdfAnalysisView.py", line 22, in <module>
    from ..controllers.ogdfAnalysis import OGDFAnalysisController
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\controllers\ogdfAnalysis.py", line 28, in <module>
    from ..network.client import Client
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\network\client.py", line 25, in <module>
    from . import handlerManager, protoParser, statusManager
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\network\protoParser.py", line 22, in <module>
    from . import handlerManager, statusManager
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\network\statusManager.py", line 24, in <module>
    from ..network.protocol.build.status_pb2 import StatusType
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\network\protocol\build\status_pb2.py", line 16, in <module>
    from . import meta_pb2 as meta__pb2
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\spanners_plugin\network\protocol\build\meta_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\google\protobuf\descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```
ee_plugin 0.0.6, QGIS 3.28.4-Firenze on Windows 10

**Comment by XavierCLL** [comment]
it seems like a bot
