### ISSUE TITLE
Error de autenticación

### ISSUE THREAD

**Issue by danielricardogarcia** [gee-community/qgis-earthengine-plugin#127]
Al intentar importar GEE en QGIS, tengo problemas de autenticación en algunas computadoras. Aclaro que en algunas computadoras corre de manera perfecta, pero en otras no permite autenticarse y da un error  como el siguiente: 
exec(open('C:/Users/ICF/AppData/Local/Temp/tmprtmgj0a4.py'.encode('utf-8')).read())
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "C:/Users/ICF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\_init.py", line 36, in __wrapping_ee_import_
    module.Initialize()
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\_init_.py", line 123, in Initialize
    http_transport=http_transport)
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 210, in initialize
    _install_cloud_api_resource()
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 287, in _install_cloud_api_resource
    http_transport=_http_transport)
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\_cloud_api_utils.py", line 149, in build_cloud_resource
    model=alt_model)
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\discovery.py", line 246, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\discovery.py", line 305, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\auth\credentials.py", line 124, in before_request
    self.refresh(request)
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\credentials.py", line 183, in refresh
    self._scopes,
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Users\ICF\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')

Si alguien tiene una idea de como solucionarlo, agradezco sus respuestas.

**Comment by XavierCLL** [comment]
Hola @danielricardogarcia,

Muy probablemente se deba a que en las computadoras que no te sirve tenga las credenciales con la vieja version del API de Google Earth Engine, para eso borra el siguiente archivo:

> 'C:\\Users\USER\.config\earthengine\credentials' 

En tu caso seria como:

> 'C:\\Users\ICF\.config\earthengine\credentials' 

Reinicia Qgis e intenta de nuevo.

**Comment by XavierCLL** [comment]
Lo voy a cerrar por inactividad pero por favor reportame si aun con la sugerencia que te indique, continuas con el mismo problema y lo volvemos a abrir. Saludos

**Comment by danielricardogarcia** [comment]
Buenas noches, Xavier.

Muchas gracias. Excelente respuesta. Funcionó perfecto.

Te agradezco mucho, y además te comento que es una herramienta que nos es
de mucha utilidad para el monitoreo de la deforestación en áreas protegidas.

Saludos

Att. Daniel Garcia
