### ISSUE TITLE
TimeoutError: [WinError 10060]

### ISSUE THREAD

**Issue by 9wangsad** [gee-community/qgis-earthengine-plugin#129]
Hello everyone, I am from China. It emerges that when I try to install and use GEE plugin. I am so confused. Could anyone know it and help me? Thanks so much.
- [ ] 

# Python Console
# Use iface to access QGIS API interface or type help(iface) for more info
# Security warning: typing commands from an untrusted source can harm your computer
import ee
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users/w/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 42, in __wrapping_ee_import__
    _module_.Initialize(http_transport=httplib2.Http())
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 131, in Initialize
    data.initialize(
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 199, in initialize
    _install_cloud_api_resource()
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 258, in _install_cloud_api_resource
    _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\_cloud_api_utils.py", line 178, in build_cloud_resource
    resource = build(static_discovery=False)
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\_cloud_api_utils.py", line 162, in build
    return discovery.build(
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\discovery.py", line 287, in build
    content = _retrieve_discovery_doc(
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\discovery.py", line 422, in _retrieve_discovery_doc
    resp, content = req.execute(num_retries=num_retries)
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google_auth_httplib2.py", line 209, in request
    self.credentials.before_request(self._request, method, uri, request_headers)
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\auth\credentials.py", line 134, in before_request
    self.refresh(request)
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\credentials.py", line 335, in refresh
    ) = reauth.refresh_grant(
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\reauth.py", line 322, in refresh_grant
    response_status_ok, response_data, retryable_error = _client._token_endpoint_request_no_throw(
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\_client.py", line 199, in _token_endpoint_request_no_throw
    request_succeeded, response_data, retryable_error = _perform_request()
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\_client.py", line 175, in _perform_request
    response = request(
  File "C:\Users\w\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google_auth_httplib2.py", line 119, in __call__
    response, data = self.http.request(
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\httplib2\__init__.py", line 1985, in request
    (response, content) = self._request(
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\httplib2\__init__.py", line 1650, in _request
    (response, content) = self._conn_request(
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\httplib2\__init__.py", line 1557, in _conn_request
    conn.connect()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\httplib2\__init__.py", line 1391, in connect
    raise socket_err
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\httplib2\__init__.py", line 1324, in connect
    sock.connect((self.host, self.port))
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by XavierCLL** [comment]
Hi @9wangsad 

The `TimeoutError` means that your computer can not reach the Google Auth API service to initiate the Google Earth Engine. Either you are behind a firewall (China firewall?) or a proxy, try using a VPN or setup the proxy

Regards

**Comment by aSullivan-geo** [comment]
Closing for now as there has been no activity for a year. Please reopen if this is still an active issue.
