### ISSUE TITLE
Issue using gee plugin with Qgis 3.22.16

### ISSUE THREAD

**Issue by lordsalomon** [gee-community/qgis-earthengine-plugin#130]
Hello dear, Thanks again for this amazing plugin. 

I have some problem using this plugin with the latest Qgis LTR release. It works fine before for me but for now, this is the error message i got once I try running my python script : 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS 3.22.16\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 9, in <module>
  File "C:\Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\Map.py", line 25, in addLayer
    add_or_update_ee_layer(eeObject, visParams, name, shown, opacity)
  File "C:\Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 157, in add_or_update_ee_layer
    layer = add_or_update_ee_image_layer(image, name, shown, opacity)
  File "C:\Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 166, in add_or_update_ee_image_layer
    raise Exception('Layer is not an EE layer: ' + name)
Exception: Layer is not an EE layer: point

I can share the script also if necessar for fixing this.

**Comment by XavierCLL** [comment]
Hi @lordsalomon 

The error says the problem, "point" is not a GEE layer, unless you are sure that layer is a GEE layer, share your script

**Comment by aSullivan-geo** [comment]
Closing for now as there has been no activity for over a year. Please reopen if this is still an active issue.
