### ISSUE TITLE
Uncaught Exception: Cannot find exiftool, make sure to add exiftool to the system path variable.


### ISSUE THREAD

**Issue by joelruma73** [gee-community/qgis-earthengine-plugin#131]
No se pudo cargar el complemento 'vertical_photo_placer' debido a un error al llamar a su método classFactory()
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/jose.elkin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vertical_photo_placer/__init__.py", line 41, in classFactory
    from .vertical_photo_placer import VerticalPhotoPlacer
  File "/Users/jose.elkin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jose.elkin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vertical_photo_placer/vertical_photo_placer.py", line 46, in <module>
    from .model.process_metadata import ProcessMetadata
  File "/Users/jose.elkin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jose.elkin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vertical_photo_placer/model/process_metadata.py", line 31, in <module>
    from .pyexiftool import ExifTool
  File "/Users/jose.elkin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jose.elkin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vertical_photo_placer/model/pyexiftool.py", line 97, in <module>
    executable = resolveTool("exiftool")
  File "/Users/jose.elkin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vertical_photo_placer/model/utility.py", line 103, in resolveTool
    raise Exception('Cannot find {0}, make sure to add {1} to the system path variable.'.format(prog, prog))
Exception: Cannot find exiftool, make sure to add exiftool to the system path variable.

```
ee_plugin 0.0.6, QGIS 3.30.2-'s-Hertogenbosch on Darwin 22.5.0

**Comment by XavierCLL** [comment]
Hi @joelruma73 

Your problem is not due to this plugin, the issue originates because of the plugin `vertical_photo_placer` that needs the exiftool to work: https://verticalphotoplacer.github.io/VerticalPhotoPlacer/
