### ISSUE TITLE
Uncaught urllib.error.HTTPError: HTTP Error 400: Bad Request


### ISSUE THREAD

**Issue by tanatieles** [gee-community/qgis-earthengine-plugin#134]
Impossível carregar complemento 'qgis_gee_data_catalog' Devido a um erro ao chamar o método Class Factory().
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\Users\Tanatiele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 326, in _execute_cloud_call
    return call.execute(num_retries=num_retries)
  File "C:\Users\Tanatiele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Tanatiele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/algorithms?prettyPrint=false&alt=json returned "Not signed up for Earth Engine or project is not registered. Visit https://developers.google.com/earth-engine/guides/access". Details: "Not signed up for Earth Engine or project is not registered. Visit https://developers.google.com/earth-engine/guides/access">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 42, in __wrapping_ee_import__
    _module_.Initialize(http_transport=httplib2.Http())
  File "C:\Users\Tanatiele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 140, in Initialize
    ApiFunction.initialize()
  File "C:\Users\Tanatiele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\Tanatiele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 1128, in getAlgorithms
    return _cloud_api_utils.convert_algorithms(_execute_cloud_call(call))
  File "C:\Users\Tanatiele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 328, in _execute_cloud_call
    raise _translate_cloud_exception(e)
ee.ee_exception.EEException: Not signed up for Earth Engine or project is not registered. Visit https://developers.google.com/earth-engine/guides/access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_gee_data_catalog\__init__.py", line 33, in classFactory
    from .qgis_gee_data_catalog import GeeDataCatalog
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_gee_data_catalog\qgis_gee_data_catalog.py", line 26, in <module>
    from .ee_interface import (add_ee_image_layer, download_ee_image_layer,
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_gee_data_catalog\ee_interface.py", line 6, in <module>
    import ee
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 44, in __wrapping_ee_import__
    if authenticate(ee=_module_):
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 84, in authenticate
    response = urllib.request.urlopen(ee.oauth.TOKEN_URI, data).read().decode()
  File "C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\PROGRA~1\QGIS32~1.13\apps\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

```
ee_plugin 0.0.6, QGIS 3.28.13-Firenze on Windows 10

**Comment by aSullivan-geo** [comment]
Hey there, is this still an issue?
