### ISSUE TITLE
Uncaught SyntaxError: invalid syntax


### ISSUE THREAD

**Issue by tanatieles** [gee-community/qgis-earthengine-plugin#135]
Impossível carregar complemento 'HelloServer' Devido a um erro ao chamar o método Class Factory().
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HelloServer\__init__.py", line 7, in classFactory
    from HelloServer import HelloServer
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HelloServer\HelloServer.py", line 154
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```
ee_plugin 0.0.6, QGIS 3.28.13-Firenze on Windows 10

**Comment by gena** [comment]
duplicate of #136
