### ISSUE TITLE
Uncaught SyntaxError: invalid syntax


### ISSUE THREAD

**Issue by tanatieles** [gee-community/qgis-earthengine-plugin#136]
Impossível carregar complemento 'wps4server' Devido a um erro ao chamar o método Class Factory().
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps4server\__init__.py", line 32, in classFactory
    from .wps4server import wps4server
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Tanatiele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps4server\wps4server.py", line 214
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```
ee_plugin 0.0.6, QGIS 3.28.13-Firenze on Windows 10

**Comment by gena** [comment]
this looks like something to do with the wps4server, please uninstall it and see if this helps

**Comment by 7yl4r** [comment]
This syntax error has to do with changes between python2 and python3. The version of wps4server you are using is python2 and the environment you are using is running python3. wps4server needs to be updated or you need to roll everything back to use a python2 interpreter.
