### ISSUE TITLE
Project Selection: Replace text input with a project selection dropdown

### ISSUE THREAD

**Issue by zacdezgeo** [gee-community/qgis-earthengine-plugin#166]
The current project selection workflow in the plugin requires users to manually input a Google Cloud project name as a text string. This input is then sent to Earth Engine (EE) without any validation, which can lead to errors if the project name is misspelled or unregistered for Earth Engine access.

To improve the user experience, the plugin should allow users to select a Google Cloud project from a dropdown list, similar to how the Earth Engine Code Editor handles project selection. The dropdown should fetch and display only active projects associated with the user’s account.

Related links:
- #156
- #150

**Comment by jdbcode** [comment]
@naschmitz for awareness. RE project listing and selection.

**Comment by naschmitz** [comment]
This is something the Earth Engine Python team is thinking about as well.

`517222506229` is the `ee-api-python-authenticator` project. We shouldn't be using that client project for Cloud Resource Manager requests.

I'm unable to reproduce the issue you're seeing, but I have a couple ideas for fixes:

- We still support the notebook auth mode. Authenticate with `ee.Authenticate(auth_mode="notebook")` and a project selector appears in the notebook authenticator. The application default credentials will store project information, so no need to specify project in `ee.Initialize`. I believe this is what the QGIS plugin was doing before we switched the default auth mode but I'm not sure.
- You could try using the Cloud Resource Manager client library: https://cloud.google.com/python/docs/reference/cloudresourcemanager/0.30.5. It'll be easier and more robust than using the  cloudresourcemanager Discovery API.
- You could also try creating credentials using the `google.auth` module instead of using the ones created by Earth Engine: `import google.auth` and `credentials, project = google.auth.default()`.

I'm happy to dig into this problem more later in the week. Let me know if any of those suggestions work for you.

**Comment by alukach** [comment]
@naschmitz Thanks for the input. Having spent some time with your suggestions:

> I'm unable to reproduce the issue you're seeing

I'm not entirely sure what you're saying here. Are you suggesting that you are able to successfully query projects with the `ee-api-python-authenticator` client?

> * We still support the notebook auth mode. Authenticate with ee.Authenticate(auth_mode="notebook") and a project selector appears in the notebook authenticator. The application default credentials will store project information, so no need to specify project in ee.Initialize. I believe this is what the QGIS plugin was doing before we switched the default auth mode but I'm not sure.

I experimented with this. I was happy to see that the goal of Project Selection was handled within the browser during the auth flow.  However, two disadvantages seemed to stand out to me:

1. The messaging during the notebook auth process is centered around authenticating _notebooks_ (to no surprise).  This could be a bit confusing to end users.
2. It appears that the output of this auth flow is to provide an auth token that is to be copied/pasted into the notebook.  This makes sense, as notebooks are unable to support redirects in the same way that traditional web servers (at least, as far as I know). The means that to use this flow within our QGIS application, we would need to present an input form to the user to allow them to provide their auth token to QGIS. This is not difficult in terms of implementation, however we need agreement that this is an acceptable UX for users of this QGIS plugin.

<details>

<summary>Screenshots</summary>

## Project Selection

<img width="513" alt="project selection" src="https://github.com/user-attachments/assets/1535033e-0e52-4d15-8356-d0e317ec95b0" />

## Auth Token Output

<img width="513" alt="auth token" src="https://github.com/user-attachments/assets/ccc3c262-61fb-42b4-80fd-cc1d4c7c58cd" />

</details>

> * You could try using the Cloud Resource Manager client library: https://cloud.google.com/python/docs/reference/cloudresourcemanager/0.30.5. It'll be easier and more robust than using the cloudresourcemanager Discovery API.
> * You could also try creating credentials using the google.auth module instead of using the ones created by Earth Engine: import google.auth and credentials, project = google.auth.default().

Regarding both of these suggestions, I don't believe that using either alternative SDK resolves the core issue of _permissions_. Take the following script for example:

```py
#!/usr/bin/env python3
# /// script
# dependencies = [
#     "google-auth",
#     "google-auth-oauthlib",
#     "google-cloud-resource-manager",
# ]
# ///

import google_auth_oauthlib.flow
from google.cloud import resourcemanager_v3


SCOPES = [
    "https://www.googleapis.com/auth/earthengine",
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/devstorage.full_control",
]

client_config = {
    "installed": {
        "client_id": "517222506229-vsmmajv00ul0bs7p89v5m89qs8eb9359.apps.googleusercontent.com",
        "client_secret": "RUP0RZ6e0pPhDzsqIJ7KlNd1",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "redirect_uris": ["http://localhost:8080"],
    }
}

flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_config(
    client_config, SCOPES
)

flow.run_local_server()
session = flow.authorized_session()

client = resourcemanager_v3.ProjectsClient(credentials=session.credentials)
for project in client.list_projects():
    print(project)

```

<details>

<summary><pre>google.api_core.exceptions.PermissionDenied</pre></summary>


```py
Traceback (most recent call last):
  File "/Users/alukach/github/gee-community/qgis-earthengine-plugin/script.py", line 41, in <module>
    for project in client.list_projects():
                   ~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/alukach/github/gee-community/qgis-earthengine-plugin/extlibs/google/cloud/resourcemanager_v3/services/projects/client.py", line 904, in list_projects
    response = rpc(
        request,
    ...<2 lines>...
        metadata=metadata,
    )
  File "/Users/alukach/github/gee-community/qgis-earthengine-plugin/extlibs/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/alukach/github/gee-community/qgis-earthengine-plugin/extlibs/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
        target,
    ...<3 lines>...
        on_error=on_error,
    )
  File "/Users/alukach/github/gee-community/qgis-earthengine-plugin/extlibs/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
    ~~~~~~~~~~~~~~~~~~~^
        exc,
        ^^^^
    ...<6 lines>...
        timeout,
        ^^^^^^^^
    )
    ^
  File "/Users/alukach/github/gee-community/qgis-earthengine-plugin/extlibs/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/alukach/github/gee-community/qgis-earthengine-plugin/extlibs/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/Users/alukach/github/gee-community/qgis-earthengine-plugin/extlibs/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/alukach/github/gee-community/qgis-earthengine-plugin/extlibs/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Cloud Resource Manager API has not been used in project 517222506229 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=517222506229 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [reason: "SERVICE_DISABLED"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "cloudresourcemanager.googleapis.com"
}
metadata {
  key: "serviceTitle"
  value: "Cloud Resource Manager API"
}
metadata {
  key: "containerInfo"
  value: "517222506229"
}
metadata {
  key: "consumer"
  value: "projects/517222506229"
}
metadata {
  key: "activationUrl"
  value: "https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=517222506229"
}
, locale: "en-US"
message: "Cloud Resource Manager API has not been used in project 517222506229 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=517222506229 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
, links {
  description: "Google developers console API activation"
  url: "https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=517222506229"
}
]
```
</details>


---

It seems like our solutions are to either:

1. Create a new OAuth2 client with the required permissions. I am unaware of what the downstream effects of that could be.
2. Update the existing OAuth2 client to have permission to list projects. I am unaware of what the downstream effects of that could be.
3. Adapt the QGIS Plugin auth flow to follow a copy/paste auth code strategy as described above. With this strategy, project selection takes place within the browser.
4. Keep the plugin as it is today where a project ID must be manually provided by text input.

**Comment by aSullivan-geo** [comment]
From Nate - 

Hi Alicia,

Sorry for the late reply. I've been OOO.

I'm not sure what the downstream effects of (1) and (2) would be and I don't have time in the next few weeks to dig around.

For now, I recommend (3) or (4). (4) is how we're solving this problem in the Python client libs, but we have plans to improve on (4) with an interactive project selection widget long term.

Thanks,
Nate

------
Given the above, lets go with option 4, and leave the plugin as it is today. 
I think we can provide some guidance in the documentation or even the UI to help users find where the project id is and make it a simple copy paste. This is how we did it in the ArcGIS tool as well. See the "authentication tools" section in that repo

**Comment by zacdezgeo** [comment]
@aSullivan-geo; Would we want this to be in the README and the https://gee-community.github.io/qgis-earthengine-plugin/ documentation site?

**Comment by zacdezgeo** [comment]
As flagged by @spatialthoughts, this remains a high-priority in his opinion for users.
