### ISSUE TITLE
EE_Plugin doesn't starts from QGIS 3.10 

### ISSUE THREAD

**Issue by Antoviscomi** [gee-community/qgis-earthengine-plugin#36]
Hi all,
I noticed that EE plugin don't starts by QGIS 3.10

Versione di QGIS 3.10.0-A Coruña build QGIS 5a8dfa62fe running on Windows 7.
at QGIS startup the token appear but when I past authorization code It come out with the following error message
I Tried to run earthengine by conda and It run succesfully

Impossibile caricare il plugin 'ee_plugin' a causa di un errore chiamando il metodo classFactory() 

ee.ee_exception.EEException: Server returned HTTP code: 404 
Traceback (most recent call last):
  File "C:/Users/XW4400/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 19, in init
    ee.Initialize()
  File "C:\Users\XW4400\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 123, in Initialize
    ApiFunction.initialize()
  File "C:\Users\XW4400\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\XW4400\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 952, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Users\XW4400\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 1797, in send_
    'Server returned HTTP code: %d' % response.status)
ee.ee_exception.EEException: Server returned HTTP code: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/XW4400/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 25, in classFactory
    from .ee_plugin import GoogleEarthEnginePlugin
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/XW4400/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_plugin.py", line 26, in 
    ee_plugin.ee_auth.init()
  File "C:/Users/XW4400/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 22, in init
    ee.Initialize()  # retry initialization once the user logs in
  File "C:\Users\XW4400\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 123, in Initialize
    ApiFunction.initialize()
  File "C:\Users\XW4400\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\XW4400\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 952, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Users\XW4400\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 1797, in send_
    'Server returned HTTP code: %d' % response.status)
ee.ee_exception.EEException: Server returned HTTP code: 404

Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.10.0-A Coruña A Coruña, 5a8dfa62fe 

Best Regards 
Antonio

**Comment by PyDG** [comment]
I run into the same problem with QGIS 3.10:: 

"Couldn't load plugin 'ee_plugin' due to an error when calling its classFactory() method 
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}') 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/%%%%%%%%%%%%%%%%%%%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 25, in classFactory
    from .ee_plugin import GoogleEarthEnginePlugin
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/%%%%%%%%%%%%%%%%%%%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_plugin.py", line 26, in 
    ee_plugin.ee_auth.init()
  File "C:/Users/%%%%%%%%%%%%%%%%%%%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 19, in init
    ee.Initialize()
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 123, in Initialize
    ApiFunction.initialize()
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 952, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 1762, in send_
    response, content = send_with_backoff()
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 1753, in send_with_backoff
    url, method=opt_method, body=payload, headers=headers)
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\auth\credentials.py", line 124, in before_request
    self.refresh(request)
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\credentials.py", line 152, in refresh
    self._scopes,
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\_client.py", line 241, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\_client.py", line 115, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.0-A Coruña A Coruña, 6ffa89eb3e 

Python Path:
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python
C:/Users/%%%%%%%%%%%%%%%%%%%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/%%%%%%%%%%%%%%%%%%%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/%%%%%%%%%%%%%%%%%%%%/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\%%%%%%%%%%%%%%%%%%%%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows"

**Comment by SiggyF** [comment]
Can you try to authenticate outside the plugin. Fo  example  using:
`conda install earthengine-api` and then run `earthengine authenticate`?

**Comment by PyDG** [comment]
re-authenticating outside the plugin seems to have solved the problem. 
Thanks!

**Comment by SiggyF** [comment]
Added a [FAQ section](https://github.com/gee-community/qgis-earthengine-plugin/blob/master/README.md#faq) with info about resetting the authentication.
