### ISSUE TITLE
Cannot install google earth engine plugin

### ISSUE THREAD

**Issue by nguyenvanthi2020** [gee-community/qgis-earthengine-plugin#51]
I use QGIS 3.12 on Windows 7
I install GEE plugin, but when I paste the authentication code into the verification box, I get error:

Couldn't load plugin 'ee_plugin' due to an error when calling its classFactory() method 

ee.ee_exception.EEException: Server returned HTTP code: 404 

Traceback (most recent call last):
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 19, in init
    ee.Initialize()
  File "C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 123, in Initialize
    ApiFunction.initialize()
  File "C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 952, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 1797, in send_
    'Server returned HTTP code: %d' % response.status)
ee.ee_exception.EEException: Server returned HTTP code: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 25, in classFactory
    from .ee_plugin import GoogleEarthEnginePlugin
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_plugin.py", line 26, in 
    ee_plugin.ee_auth.init()
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 22, in init
    ee.Initialize()  # retry initialization once the user logs in
  File "C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 123, in Initialize
    ApiFunction.initialize()
  File "C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 952, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 1797, in send_
    'Server returned HTTP code: %d' % response.status)
ee.ee_exception.EEException: Server returned HTTP code: 404

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] 
QGIS version: 3.12.0-București București, cd141490ec 

Python Path:

C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.12\apps\Python37
C:\PROGRA~1\QGIS3~1.12\apps\Python37\Scripts
C:\Program Files\QGIS 3.12\bin\python37.zip
C:\PROGRA~1\QGIS3~1.12\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib
C:\Program Files\QGIS 3.12\bin
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\Pythonwin
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows

Please help me to resolve this issue,

Thank you in advance,

Thi

**Comment by gena** [comment]
Try to authenticate outside of the QGIS, the plugin uses the same auth info as the EE CLI: https://github.com/gee-community/qgis-earthengine-plugin#faq.

**Comment by jctull** [comment]
Also make sure that your google [account has approval](https://signup.earthengine.google.com) to use google earth engine.

**Comment by gena** [comment]
Closing for no activity
