### ISSUE TITLE
mac os cannot load the plugin, but the earthengine authenticate has been successfully verified

### ISSUE THREAD

**Issue by mty0716** [gee-community/qgis-earthengine-plugin#55]
I can download the plugin, but it can't work. This is the error.

Unable to load plugin "ee_plugin" due to an error when calling its classFactory() method

TimeoutError: [Errno 60] Operation timed out 
Traceback (most recent call last):
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 25, in classFactory
    from .ee_plugin import GoogleEarthEnginePlugin
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/ee_plugin.py", line 26, in 
    ee_plugin.ee_auth.init()
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/ee_auth.py", line 19, in init
    ee.Initialize()
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/ee/__init__.py", line 123, in Initialize
    ApiFunction.initialize()
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/ee/apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/ee/data.py", line 952, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/ee/data.py", line 1762, in send_
    response, content = send_with_backoff()
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/ee/data.py", line 1753, in send_with_backoff
    url, method=opt_method, body=payload, headers=headers)
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/google/auth/credentials.py", line 124, in before_request
    self.refresh(request)
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/google/oauth2/credentials.py", line 152, in refresh
    self._scopes,
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/google/oauth2/_client.py", line 241, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/google/oauth2/_client.py", line 105, in _token_endpoint_request
    response = request(method="POST", url=token_uri, headers=headers, body=body)
  File "/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin/google_auth_httplib2.py", line 116, in __call__
    url, method=method, body=body, headers=headers, **kwargs)
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/httplib2/__init__.py", line 1926, in request
    cachekey,
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/httplib2/__init__.py", line 1501, in _conn_request
    conn.connect()
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/httplib2/__init__.py", line 1356, in connect
    raise socket_err
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/httplib2/__init__.py", line 1289, in connect
    sock.connect((self.host, self.port))
TimeoutError: [Errno 60] Operation timed out

Python版本： 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS版本： 3.10.6-A Coruña A Coruña, ec80021f49 

Python路径：
/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geohey_toolbox
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python
/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.10.app/Contents/Resources/python
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/mty/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_darwin

**Comment by gena** [comment]
Are you sure you are not under a firewall? Does the command-line version work - check the FAQ: https://github.com/gee-community/qgis-earthengine-plugin#faq?

**Comment by gena** [comment]
Please reopen if this is still an issue, make sure to use the latest version for now 0.0.2
