### ISSUE TITLE
Error in Installing the qgis-earthengine-plugin

### ISSUE THREAD

**Issue by engrprecious** [gee-community/qgis-earthengine-plugin#57]
Trying to install qgis-earthengine-plugin, this is what i get. Can anyone explain what is happening and help out?

Couldn't load plugin 'qgis-earthengine-plugin-master' due to an error when calling its classFactory() method 

ImportError: cannot import name 'provider' from 'ee_plugin' (C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py) 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-earthengine-plugin-master\__init__.py", line 25, in classFactory
    from .ee_plugin import GoogleEarthEnginePlugin
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-earthengine-plugin-master\ee_plugin.py", line 26, in 
    from ee_plugin import provider
ImportError: cannot import name 'provider' from 'ee_plugin' (C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py)

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.2-București București, 8a1fb33634 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\libs
C:\Users\Lenovo\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlrd-1.2.0-py2.py3-none-any.whl
C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlwt-1.3.0-py2.py3-none-any.whl
C:\Users\Lenovo\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis-earthengine-plugin-master\extlibs_windows
C:\Users\Lenovo\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis-earthengine-plugin-master\extlibs_windows

**Comment by gena** [comment]
Are you able to use EE from Code Editor and can you install/run earthengine-api from the comand-line? Using your default python (not the one within QGIS). 

Check some common problems here https://github.com/gee-community/qgis-earthengine-plugin#faq?

**Comment by gena** [comment]
Closed for no activity, the error is most probably fixed by #82
