### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'giswater_qgis_plugin-master-3'


### ISSUE THREAD

**Issue by Almavin** [gee-community/qgis-earthengine-plugin#97]
Couldn't load plugin 'giswater_qgis_plugin-master-3.4'
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/Users/Nzumi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'giswater_qgis_plugin-master-3'

```
ee_plugin 0.0.4, QGIS 3.16.3-Hannover on Windows 10

**Comment by XavierCLL** [comment]
Hi, this error is not related to this plugin, that shows that you have a problem with the Giswater Qgis plugin, try to delete it first.
